/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import conector.Conector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IFSP
 */
public class TelaPersonagens extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuarios
     */
    public TelaPersonagens() {
        initComponents();
        //Centraliza a tela no monitor
        this.setLocationRelativeTo(null);
        //desabilita o botão excluir
        btnEcluir.setEnabled(false);
        PopulaJtable();
        PopulaJtable2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtClasse = new javax.swing.JTextField();
        txtRaca = new javax.swing.JTextField();
        brnSalvar = new javax.swing.JButton();
        btnEcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPersonagens = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPlayer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtStg = new javax.swing.JTextField();
        txtDtx = new javax.swing.JTextField();
        txtInt = new javax.swing.JTextField();
        txtCons = new javax.swing.JTextField();
        txtCha = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtStatus = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de usuários");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Personagens");

        jLabel2.setText("Nome");

        jLabel3.setText("Classe");

        jLabel4.setText("Raça");

        brnSalvar.setText("Salvar");
        brnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnSalvarActionPerformed(evt);
            }
        });

        btnEcluir.setText("Excluir");
        btnEcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcluirActionPerformed(evt);
            }
        });

        jtPersonagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Player", "Sexo", "Classe", "Raça"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtPersonagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPersonagensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPersonagens);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        jLabel5.setText("Personagens");

        jLabel6.setText("ID");

        txtID.setEditable(false);
        txtID.setEnabled(false);
        txtID.setFocusable(false);

        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });

        jLabel7.setText("Sexo");

        jLabel9.setText("Player");

        jLabel8.setText("Força");

        jLabel10.setText("Destreza");

        jLabel11.setText("Inteligencia");

        jLabel12.setText("Constituição");

        jLabel13.setText("Carisma");

        txtInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntActionPerformed(evt);
            }
        });

        txtCha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChaActionPerformed(evt);
            }
        });

        jtStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Força", "Destreza", "Inteligencia", "Constituição", "Carisma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtStatus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(22, 22, 22)
                                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(btnNovo)
                                                                .addGap(59, 59, 59)
                                                                .addComponent(brnSalvar))
                                                            .addComponent(txtRaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(75, 75, 75)
                                                        .addComponent(btnEcluir)))))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txtStg, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtCha, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                .addComponent(txtCons))
                                            .addComponent(txtInt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDtx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtStg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(txtDtx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(txtCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnNovo)
                                    .addComponent(brnSalvar)
                                    .addComponent(btnEcluir)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtCha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcluirActionPerformed
        String strID = txtID.getText();
        int opcao;
        opcao = JOptionPane.showConfirmDialog(
                null, 
                "Deseja excluir?",
                "Excluir?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                 null);
        if(opcao == 0){
            //exclui o registro
            Conector conector = new Conector();
            Connection con = (Connection) 
                conector.getConnection();
            PreparedStatement stm = null;
            String sql = 
                    "DELETE from Personagem where "
                    + "id = ?;";
            try {
                stm = con.prepareStatement(sql);
                stm.setString(1, strID);
                stm.execute();
                JOptionPane.
                        showMessageDialog(null, 
                                "Personagem excluido");
                stm.close();
                con.close();
                PopulaJtable();
                PopulaJtable2();
                txtID.setText("");
                txtNome.setText("");
                txtRaca.setText("");
                txtClasse.setText("");
                txtPlayer.setText("");
                txtSexo.setText("");
                txtStg.setText("");
                txtDtx.setText("");
                txtInt.setText("");
                txtCons.setText("");
                txtCha.setText("");
                
                btnEcluir.setEnabled(false);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
                
        }
    }//GEN-LAST:event_btnEcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtID.setText("");
        txtNome.setText("");
        txtRaca.setText("");
        txtClasse.setText("");
        txtPlayer.setText("");
        txtSexo.setText("");
        txtStg.setText("");
        txtDtx.setText("");
        txtInt.setText("");
        txtCons.setText("");
        txtCha.setText("");
        
        btnEcluir.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void jtPersonagensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPersonagensMouseClicked
        int linha = 
                jtPersonagens.getSelectedRow();
        txtID.setText(
           jtPersonagens.getValueAt(linha, 0).
                   toString());
        txtNome.setText(
            jtPersonagens.getValueAt(linha, 1).
                    toString());
        txtClasse.setText(
            jtPersonagens.getValueAt(linha, 4).
                    toString());
        txtPlayer.setText(
            jtPersonagens.getValueAt(linha, 2).
                    toString());
        txtRaca.setText(
            jtPersonagens.getValueAt(linha, 5).
                    toString());
        txtSexo.setText(
            jtPersonagens.getValueAt(linha, 3).
                    toString());
        
        txtStg.setText(
            jtStatus.getValueAt(linha, 0).
                    toString());
        txtDtx.setText(
             jtStatus.getValueAt(linha, 1).
                     toString());
        txtInt.setText(
            jtStatus.getValueAt(linha, 2).
                    toString());
        txtCons.setText(
            jtStatus.getValueAt(linha, 3).
                    toString());
        txtCha.setText(
            jtStatus.getValueAt(linha, 4).
                    toString());
            
        btnEcluir.setEnabled(true);
    }//GEN-LAST:event_jtPersonagensMouseClicked

    private void brnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnSalvarActionPerformed
        String strID = 
                txtID.getText();
        String strNome = 
                txtNome.getText();
        String strClasse = 
                txtClasse.getText();
        String strRaca = 
                txtRaca.getText();
        String strPlayer = 
                txtPlayer.getText();
        String strSexo = 
                txtSexo.getText();
        String strStg = 
                txtStg.getText();
        String strDtx = 
                txtDtx.getText();
        String strInt = 
                txtInt.getText();
        String strCons = 
                txtCons.getText();
        String strCha = 
                txtCha.getText();
        
        if(strID.equals("")){
            //Verifica os campos vazios
            if(strNome.equals("") || 
                    strClasse.equals("") ||
                    strRaca.equals("") ||
                    strPlayer.equals("") ||
                    strSexo.equals("") ||
                    strStg.equals("") ||
                    strDtx.equals("") ||
                    strInt.equals("") ||
                    strCons.equals("") ||
                    strCha.equals("")){
                String strMsg = 
                        "Preencha todos"
                    + " os campos para "
                    + "salvar";
                JOptionPane.showMessageDialog(
                        null, strMsg);
            }else{
                //insere no banco
                String sql = "INSERT INTO Personagem "
                        + "(nome, player, Classe, Raca, Sexo, Stg, Dtx, Inte, Cons, Cha) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                Conector conector = new Conector();
                Connection con = conector.getConnection(); 
                try {
                    PreparedStatement stm =
                            con.prepareStatement(sql);
                    stm.setString(1, strNome);
                    stm.setString(2, strPlayer);
                    stm.setString(3, strClasse);
                    stm.setString(4, strRaca);
                    stm.setString(5, strSexo);
                    stm.setString(6, strStg);
                    stm.setString(7, strDtx);
                    stm.setString(8, strInt);
                    stm.setString(9, strCons);
                    stm.setString(10, strCha);
                    stm.execute();
                    stm.close();
                    con.close();
                    JOptionPane.showMessageDialog(
                        null, "Personagem inserido!");
                    txtID.setText("");
                    txtNome.setText("");
                    txtRaca.setText("");
                    txtClasse.setText("");
                    txtPlayer.setText("");
                    txtSexo.setText("");
                    txtStg.setText("");
                    txtDtx.setText("");
                    txtInt.setText("");
                    txtCons.setText("");
                    txtCha.setText("");
                    
                    PopulaJtable();
                    PopulaJtable2();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(
                        null, ex);
                }
            }
        }
    }//GEN-LAST:event_brnSalvarActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntActionPerformed

    private void txtChaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPersonagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPersonagens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnSalvar;
    private javax.swing.JButton btnEcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jtPersonagens;
    private javax.swing.JTable jtStatus;
    private javax.swing.JTextField txtCha;
    private javax.swing.JTextField txtClasse;
    private javax.swing.JTextField txtCons;
    private javax.swing.JTextField txtDtx;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtInt;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPlayer;
    private javax.swing.JTextField txtRaca;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtStg;
    // End of variables declaration//GEN-END:variables

    private void PopulaJtable() {
        String sql = 
         "SELECT id, nome, player, sexo, classe, raca FROM Personagem";
        try {
            Conector conector = new Conector();
            Connection con =
            conector.getConnection();        
            PreparedStatement banco =
                    con.prepareStatement(sql);
            banco.execute();
            ResultSet resultado =
                    banco.executeQuery(sql);
            DefaultTableModel model = 
                    (DefaultTableModel) 
                    jtPersonagens.getModel();
            model.setNumRows(0);
            while (resultado.next()){
                model.addRow(new Object[]{
                    resultado.getString("ID"),
                    resultado.getString("nome"),
                    resultado.getString("player"),
                    resultado.getString("sexo"),
                    resultado.getString("classe"),
                    resultado.getString("raca")
                });
            }
            banco.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
    private void PopulaJtable2() {
        String sql = 
         "SELECT id, stg, dtx, inte, cons, cha FROM Personagem";
        try {
            Conector conector = new Conector();
            Connection con =
            conector.getConnection();        
            PreparedStatement banco =
                    con.prepareStatement(sql);
            banco.execute();
            ResultSet resultado =
                    banco.executeQuery(sql);
            DefaultTableModel model = 
                    (DefaultTableModel) 
                    jtStatus.getModel();
            model.setNumRows(0);
            while (resultado.next()){
                model.addRow(new Object[]{
                    resultado.getString("stg"),
                    resultado.getString("dtx"),
                    resultado.getString("inte"),
                    resultado.getString("cons"),
                    resultado.getString("cha")
                });
            }
            banco.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
}
